<?php
/**
 * @var $block \Topsort\Integration\Block\Catalog\Product\ListImpressions
 */
?>
<script type="text/javascript">
    require(["jquery"], function ($) {
        $(document).ready(function () {
            // send request with some delay to let the important content (e.g. promotions) to be loaded first
            setTimeout(function () {
                $.ajax({
                    url: "<?= $block->getImpressionsTrackingUrl() ?>",
                    type: 'GET',
                    async: true,
                    dataType: 'json'
                });
            }, 3000);
        });
    });
</script>