<?php
/** @var \Topsort\Integration\Block\PromotedProductsLoader $block */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Topsort_Integration/js/promoted-products": {
                "loaderIcon": "<?= $block->getLoaderIconUrl() ?>",
                "loadPromotionsUrl": "<?= $block->getLoadPromotionsUrl() ?>",
                "loaderMaskContainer": "<?= $block->getLoaderMaskContainerSelector() ?>",
                "productsContainer": "<?= $block->getProductsContainerSelector() ?>",
                "toolbarSelector": "<?= $block->getToolbarSelector() ?>"
            }
        }
    }
</script>