<?php
/** @var $block \Magento\Catalog\Block\Product\Image */
$originalBlock = clone $block;
$originalBlock->setTemplate('Magento_Catalog::product/image_with_borders.phtml');
echo $originalBlock->toHtml();
?>

<?php if ($block->getIsPromoted()) : ?>
<script type="text/javascript">
    require(["jquery"],function($) {
        $(document).ready(function() {
            let promotedLabel = document.createElement( "div" );
            promotedLabel.setAttribute('class', "topsort-promoted-indicator");
            promotedLabel.appendChild(document.createTextNode('<?= $block->escapeHtml($block->getPromotedLabelText()) ?>'));
            $('.product-image-container-<?= /* @noEscape */ $block->getProductId() ?> .product-image-wrapper')[0].prepend(promotedLabel);
        });
    });
</script>
<?php endif; ?>