<?php
/** @var $block \Magento\Catalog\Block\Product\Image */
$originalBlock = clone $block;
$originalBlock->setTemplate('Magento_Catalog::product/image_with_borders.phtml');
echo $originalBlock->toHtml();
?>

<?php if ($block->getIsPromoted()) : ?>
<span class="topsort-promoted-product-identifier-<?= /* @noEscape */ $block->getProductId() ?>"></span>
<script type="text/javascript">
    require(["jquery"],function($) {
        $(document).ready(function() {
            let promotedLabel = document.createElement( "div" );
            promotedLabel.setAttribute('class', "topsort-promoted-indicator");
            promotedLabel.appendChild(document.createTextNode('<?= $block->escapeHtml($block->getPromotedLabelText()) ?>'));
            $('.topsort-promoted-product-identifier-<?= /* @noEscape */ $block->getProductId() ?>').parents('.product-item-info').find('.product-image-wrapper').prepend(promotedLabel);

            //jQuery('#product-item-info_338 a[href="#"]') // on-page action-links
        });
    });
</script>
<?php endif; ?>